# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  invoiceservice:
    image: invoiceservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5298:5298
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
